# Generated by Django 5.2.4 on 2025-07-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='number_of_completed_courses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
