# Generated by Django 5.2.4 on 2025-07-06 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_user_teacher_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'student'}, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
