# Generated by Django 5.2.4 on 2025-07-06 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0011_user_slug_alter_teacherprofile_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'student'}, null=True, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
