# Generated by Django 5.2.4 on 2025-07-07 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0012_alter_teacherprofile_students_remove_user_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'student'}, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
