# Generated by Django 5.2.4 on 2025-07-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0014_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
